Compiled from "TestAsyncProcess.java"
class org.apache.hadoop.hbase.client.TestAsyncProcess$CallerWithFailure extends org.apache.hadoop.hbase.client.RpcRetryingCallerImpl<org.apache.hadoop.hbase.client.AbstractResponse> {
  public org.apache.hadoop.hbase.client.TestAsyncProcess$CallerWithFailure(java.io.IOException);
    Code:
       0: aload_0
       1: ldc2_w        #1                  // long 100l
       4: ldc2_w        #3                  // long 500l
       7: bipush        100
       9: bipush        9
      11: invokespecial #5                  // Method org/apache/hadoop/hbase/client/RpcRetryingCallerImpl."<init>":(JJII)V
      14: aload_0
      15: aload_1
      16: putfield      #6                  // Field e:Ljava/io/IOException;
      19: return

  public org.apache.hadoop.hbase.client.AbstractResponse callWithoutRetries(org.apache.hadoop.hbase.client.RetryingCallable<org.apache.hadoop.hbase.client.AbstractResponse>, int) throws java.io.IOException, java.lang.RuntimeException;
    Code:
       0: aload_0
       1: getfield      #6                  // Field e:Ljava/io/IOException;
       4: athrow

  public java.lang.Object callWithoutRetries(org.apache.hadoop.hbase.client.RetryingCallable, int) throws java.io.IOException, java.lang.RuntimeException;
    Code:
       0: aload_0
       1: aload_1
       2: iload_2
       3: invokevirtual #7                  // Method callWithoutRetries:(Lorg/apache/hadoop/hbase/client/RetryingCallable;I)Lorg/apache/hadoop/hbase/client/AbstractResponse;
       6: areturn
}
