Compiled from "TestClientScanner.java"
class org.apache.hadoop.hbase.client.TestClientScanner$MockRpcRetryingCallerFactory$1 implements org.apache.hadoop.hbase.client.RpcRetryingCaller<T> {
  final org.apache.hadoop.hbase.client.TestClientScanner$MockRpcRetryingCallerFactory this$0;

  org.apache.hadoop.hbase.client.TestClientScanner$MockRpcRetryingCallerFactory$1(org.apache.hadoop.hbase.client.TestClientScanner$MockRpcRetryingCallerFactory);
    Code:
       0: aload_0
       1: aload_1
       2: putfield      #1                  // Field this$0:Lorg/apache/hadoop/hbase/client/TestClientScanner$MockRpcRetryingCallerFactory;
       5: aload_0
       6: invokespecial #2                  // Method java/lang/Object."<init>":()V
       9: return

  public void cancel();
    Code:
       0: return

  public T callWithRetries(org.apache.hadoop.hbase.client.RetryingCallable<T>, int) throws java.io.IOException, java.lang.RuntimeException;
    Code:
       0: new           #3                  // class java/io/IOException
       3: dup
       4: ldc           #4                  // String Scanner exception
       6: invokespecial #5                  // Method java/io/IOException."<init>":(Ljava/lang/String;)V
       9: athrow

  public T callWithoutRetries(org.apache.hadoop.hbase.client.RetryingCallable<T>, int) throws java.io.IOException, java.lang.RuntimeException;
    Code:
       0: aload_1
       1: iload_2
       2: invokeinterface #6,  2            // InterfaceMethod org/apache/hadoop/hbase/client/RetryingCallable.call:(I)Ljava/lang/Object;
       7: areturn
       8: astore_3
       9: aload_3
      10: athrow
      11: astore_3
      12: new           #8                  // class java/lang/RuntimeException
      15: dup
      16: aload_3
      17: invokespecial #9                  // Method java/lang/RuntimeException."<init>":(Ljava/lang/Throwable;)V
      20: athrow
    Exception table:
       from    to  target type
           0     7     8   Class java/io/IOException
           0     7    11   Class java/lang/Exception
}
