Compiled from "TestAsyncProcess.java"
class org.apache.hadoop.hbase.client.TestAsyncProcess$AsyncProcessWithFailure extends org.apache.hadoop.hbase.client.TestAsyncProcess$MyAsyncProcess {
  public org.apache.hadoop.hbase.client.TestAsyncProcess$AsyncProcessWithFailure(org.apache.hadoop.hbase.client.ClusterConnection, org.apache.hadoop.conf.Configuration, java.io.IOException);
    Code:
       0: aload_0
       1: aload_1
       2: aload_2
       3: invokespecial #1                  // Method org/apache/hadoop/hbase/client/TestAsyncProcess$MyAsyncProcess."<init>":(Lorg/apache/hadoop/hbase/client/ClusterConnection;Lorg/apache/hadoop/conf/Configuration;)V
       6: aload_0
       7: aload_3
       8: putfield      #2                  // Field ioe:Ljava/io/IOException;
      11: aload_0
      12: lconst_1
      13: putfield      #3                  // Field serverTrackerTimeout:J
      16: return

  protected org.apache.hadoop.hbase.client.RpcRetryingCaller<org.apache.hadoop.hbase.client.AbstractResponse> createCaller(org.apache.hadoop.hbase.client.CancellableRegionServerCallable, int);
    Code:
       0: aload_0
       1: getfield      #4                  // Field callsCt:Ljava/util/concurrent/atomic/AtomicInteger;
       4: invokevirtual #5                  // Method java/util/concurrent/atomic/AtomicInteger.incrementAndGet:()I
       7: pop
       8: new           #6                  // class org/apache/hadoop/hbase/client/TestAsyncProcess$CallerWithFailure
      11: dup
      12: aload_0
      13: getfield      #2                  // Field ioe:Ljava/io/IOException;
      16: invokespecial #7                  // Method org/apache/hadoop/hbase/client/TestAsyncProcess$CallerWithFailure."<init>":(Ljava/io/IOException;)V
      19: areturn
}
