Using TensorFlow backend.
/home/2014313303/.local/lib/python3.5/site-packages/sklearn/utils/validation.py:752: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
zero : 
39451

one : 
9019
hbase-AST
all data

Sentence length Average : 35

Under 10 : 21694
Over 10, Under 200 : 25475
Over 200, Under 400 : 1121
Over 400 : 180

hbase-AST
updated_train_data

Sentence length Average : 57

Under 10 : 0
Over 10, Under 200 : 22776
Over 200, Under 400 : 1062
Over 400 : 0


Test_zero:  1844
Train_zero:  16629
zero:  18473
Test_one:  763
Train_one:  7209
one:  7972


Test accuracy: 72.95350360183366

data size :  15946

zero :  7974

one :  7972

train_zero :  7210

train_one :  7209

test_zero :  764

test_one :  763

choose_zero :  953

choose_one :  574

F1score :  0.6910994764397905

AUC : 0.8351505836015178

Confusion Matrix
[[652 112]
 [301 462]]
True label 0
0.8534031413612565  
0.14659685863874344  
True label 1
0.3944954128440367  
0.6055045871559633  
Traceback (most recent call last):
  File "AdaBoost_Logging.py", line 507, in <module>
    TP_file_name = "Code_snippet/real_final/"+str(test_rate)+"/TP_"+filename+"_ep"+str(ep+1)+"_"+str(count)+".txt"
NameError: name 'ep' is not defined
