Using TensorFlow backend.
/home/2014313303/.local/lib/python3.5/site-packages/sklearn/utils/validation.py:752: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
zero : 
39451

one : 
9019
hbase-code
all data

Sentence length Average : 55

Under 10 : 8165
Over 10, Under 200 : 37669
Over 200, Under 400 : 2147
Over 400 : 489

hbase-code
updated_train_data

Sentence length Average : 56

Under 10 : 0
Over 10, Under 200 : 29835
Over 200, Under 400 : 1382
Over 400 : 0


Test_zero:  2643
Train_zero:  23540
zero:  26183
Test_one:  812
Train_one:  7677
one:  8489


Test accuracy: 74.33846153846154

data size :  16980

zero :  8491

one :  8489

train_zero :  7678

train_one :  7677

test_zero :  813

test_one :  812

choose_zero :  880

choose_one :  745

F1score :  0.7321772639691715

AUC : 0.8354987306030697

Confusion Matrix
[[638 175]
 [242 570]]
True label 0
0.7847478474784748  
0.21525215252152521  
True label 1
0.29802955665024633  
0.7019704433497537  
Traceback (most recent call last):
  File "AdaBoost_Logging_ye.py", line 503, in <module>
    train_result = hist.history
NameError: name 'hist' is not defined
